[package]
name = "computational-physics-2010"
version = "0.0.1"
authors = ["fxzjshm <fxzjshm@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
prettytable-rs = "^0.8"
